version: '3.8'

services:
  backend:
    image: <registry-name>.azurecr.io/ktor-backend:latest
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL} # Passed via Azure environment variables
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}