version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: >
      sh -c "while ! nc -z db 3306; do sleep 1; done; java -jar app.jar" # Wait for MySQL to be ready
    volumes:
      - ./logs:/usr/src/app/logs # Optional: Easily access backend logs locally

volumes:
  mysql-data: