name: Build & Deploy Ktor Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login <smartattendanceapiregistry>.azurecr.io -u <registry-name> --password-stdin

      - name: Build Docker image
        run: docker build -t smartattendanceapiregistry.azurecr.io/ktor-backend:latest .

      - name: Push Docker image
        run: docker push smartattendanceapiregistry.azurecr.io/ktor-backend:latest