name: Build & Deploy Ktor Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login smartattendanceapiregistry.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin


      - name: Build Docker image
        run: docker build -t smartattendanceapiregistry.azurecr.io/ktor-backend:latest .

      - name: Push Docker image to ACR
        run: docker push smartattendanceapiregistry.azurecr.io/ktor-backend:latest

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "smartattendance-backend"
          images: "smartattendanceapiregistry.azurecr.io/ktor-backend:latest"
        env:
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
