name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
      
      - name: Link to Railway project
        run: railway link "${{ secrets.RAILWAY_PROJECT_ID }}"
        env:
          RAILWAY_TOKEN: "${{ secrets.RAILWAY_TOKEN }}"
      
      - name: Connect to Docker service
        run: railway service "${{ secrets.RAILWAY_SERVICE_NAME }}"
        env:
          RAILWAY_TOKEN: "${{ secrets.RAILWAY_TOKEN }}"
      
      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: "${{ secrets.RAILWAY_TOKEN }}"