name: Build & Deploy Ktor Backend to Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java environment for Ktor
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # Step 3: Build Ktor backend
      - name: Run Gradle Build
        run: ./gradlew build

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: docker build -t ktor-backend:latest .

      # Step 5: Login to Railway and Push Docker Image
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --service ktor-backend
