name: Build & Deploy Ktor Backend to Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java environment for Ktor
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # Step 3: Run Gradle Build (generate the JAR)
      - name: Build Ktor backend
        run: ./gradlew build

      # Step 4: Build Docker Image (now the JAR exists)
      - name: Build Docker Image
        run: docker build -t ktor-backend:latest .

      # Step 5: Install Railway CLI
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      # Step 6: Add Railway to PATH
      - name: Add Railway to PATH
        run: echo "$HOME/.railway/bin" >> $GITHUB_PATH

      # Step 7: Login to Railway and Deploy
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway login --token $RAILWAY_TOKEN
          railway link 14e8bb3c-1a4a-40db-bb52-da85fd4d9f90
          railway up --service samrt-attendance-api
