name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Run chmod to make gradlew executble
        run: chmod +x ./gradlew
      
      - name: Build with Gradle
        run: ./gradlew shadowJar
      
      - name: Install Railway CLI
        run: npm i -g @railway/cli
      
      - name: Deploy to Railway
        run: railway up --service samrt-attendance-api
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}