mkdir -p .github/workflows
cat > .github/workflows/railway-deploy.yml << 'EOF'
name: Build & Deploy Ktor Backend to Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
          
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # Step 3: Build Shadow JAR
      - name: Build Shadow JAR
        run: ./gradlew shadowJar

      # Step 4: Verify the JAR
      - name: Verify JAR file
        run: |
          ls -la build/libs/
          du -h build/libs/app.jar

      # Step 5: Install and configure Railway CLI
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh
      
      # Step 6: Deploy to Railway
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --service smart-attendance-api --detach
EOF